name: Release

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        default: production
        options:
          - production
          - dev

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile
      - run: bun test

      - run: npm install -g @circlesac/oneup
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          oneup version

      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --tag ${{ inputs.env == 'production' && 'latest' || inputs.env }}

      - run: git push origin master --follow-tags
